Uncomment build steps in HVAC CI workflow

diff --git a/.github/workflows/hvac.yml b/.github/workflows/hvac.yml
--- a/.github/workflows/hvac.yml
+++ b/.github/workflows/hvac.yml
@@ -1,8 +1,8 @@
 name: Android CI
 
 on:
-  push:
-    branches: [ "master" ]
+  # push:
+  #   branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
 
@@ -12,31 +12,31 @@ jobs:
     runs-on: self-hosted
 
     steps:
-    # - name: Build The APK and create a IMG
-    #   run: |
-    #     echo "going to the build directory"
-    #     cd /home/ubuntu/android-automotive/
-    #     echo "Setting up mk file"
-    #     cp device/generic/car/common/module_HvacApplication device/generic/car/common/car.mk
-    #     echo "Setting up the environment"
-    #     source build/envsetup.sh
-    #     echo "Select the aosp image"
-    #     lunch aosp_car_x86_64-userdebug
-    #     echo "Build apk module"
-    #     build/soong/soong_ui.bash --make-mode -j$(nproc) HvacApplication
-    #     echo "check if build succeeded"
-    #     if [[ $? -gt 0 ]]
-    #     then
-    #         echo "remove bootstrap since build failed"
-    #         rm -rf out/soong/.bootstrap out/soong/.intermediates
-    #         echo "Rebuild the module"
-    #         build/soong/soong_ui.bash --make-mode -j$(nproc) HvacApplication
-    #     fi
-    #     echo "Check if apk is created"
-    #     ls out/target/product/generic_car_x86_64/system/app/HvacApplication/HvacApplication.apk
-    #     echo "Building Android image with the generated APK"
-    #     m snod
-    #     echo "Build complete"
+    - name: Build The APK and create a IMG
+      run: |
+        echo "going to the build directory"
+        cd /home/ubuntu/android-automotive/
+        echo "Setting up mk file"
+        cp device/generic/car/common/module_HvacApplication device/generic/car/common/car.mk
+        echo "Setting up the environment"
+        source build/envsetup.sh
+        echo "Select the aosp image"
+        lunch aosp_car_x86_64-userdebug
+        echo "Build apk module"
+        build/soong/soong_ui.bash --make-mode -j$(nproc) HvacApplication
+        echo "check if build succeeded"
+        if [[ $? -gt 0 ]]
+        then
+            echo "remove bootstrap since build failed"
+            rm -rf out/soong/.bootstrap out/soong/.intermediates
+            echo "Rebuild the module"
+            build/soong/soong_ui.bash --make-mode -j$(nproc) HvacApplication
+        fi
+        echo "Check if apk is created"
+        ls out/target/product/generic_car_x86_64/system/app/HvacApplication/HvacApplication.apk
+        echo "Building Android image with the generated APK"
+        m snod
+        echo "Build complete"
         # ---------------------
     # - name: Build with Gradle
     #   run: |
